default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  pool: 5
  host: <%= ENV.fetch('DATABASE_HOST', '127.0.0.1') %>
  port: 3306
  username: peatio
  password: Pe@tio2019

# development:
 # <<: *default
 # database: peatio_development

development:
 adapter: mysql2
 encoding: utf8
 database: peatio
 username: peatio
 password: Pe@tio2019  
# database: peatio_development

test:
  <<: *default
  database: peatio

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: 10
  database: <%= ENV.fetch('DATABASE_NAME', 'peatio') %>

#production: 
# adapter: mysql2
# encoding: utf8 
# database: peatio 
# pool: 10 
# username: peatio 
# password: Pe@tio2019 
# socket: /var/run/mysqld/mysqld.sock 
# reconnect: true
